# Generated by Django 4.0.5 on 2022-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteBooksApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
