# Generated by Django 4.0.5 on 2022-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
        ('favoriteBooksApp', '0004_book_user_who_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_who_liked',
            field=models.ManyToManyField(to='userApp.user'),
        ),
    ]
